// components/ResultDisplay.js
const ResultDisplay = ({ result, fileName, onReset }) => {
    const isAiGenerated = result.prediction === 'ai_generated';
    const confidence = Math.round(result.confidence * 100);
  
    const getResultIcon = () => {
      if (isAiGenerated) {
        return confidence > 80 ? '🤖' : '⚠️';
      }
      return confidence > 80 ? '✅' : '🤔';
    };
  
    const getResultTitle = () => {
      if (isAiGenerated) {
        return confidence > 80 ? 'Likely AI-Generated' : 'Possibly AI-Generated';
      }
      return confidence > 80 ? 'Looks Real' : 'Unclear Result';
    };
  
    const getResultColor = () => {
      if (isAiGenerated) {
        return confidence > 80 ? 'text-red-600' : 'text-orange-600';
      }
      return confidence > 80 ? 'text-green-600' : 'text-yellow-600';
    };
  
    const getResultBg = () => {
      if (isAiGenerated) {
        return confidence > 80 ? 'bg-red-50 border-red-200' : 'bg-orange-50 border-orange-200';
      }
      return confidence > 80 ? 'bg-green-50 border-green-200' : 'bg-yellow-50 border-yellow-200';
    };
  
    const getConfidenceBar = () => {
      const width = `${confidence}%`;
      let colorClass = 'bg-gray-400';
      
      if (confidence > 80) {
        colorClass = isAiGenerated ? 'bg-red-500' : 'bg-green-500';
      } else if (confidence > 60) {
        colorClass = 'bg-yellow-500';
      }
  
      return (
        <div className="w-full bg-gray-200 rounded-full h-3">
          <div 
            className={`h-3 rounded-full transition-all duration-500 ${colorClass}`}
            style={{ width }}
          />
        </div>
      );
    };
  
    return (
      <div className="bg-white rounded-2xl shadow-xl p-8">
        {/* Header */}
        <div className="text-center mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-2">
            Analysis Complete
          </h2>
          <p className="text-gray-600">
            Results for: <span className="font-medium">{fileName}</span>
          </p>
        </div>
  
        {/* Main Result */}
        <div className={`border-2 rounded-xl p-6 mb-6 ${getResultBg()}`}>
          <div className="text-center">
            <div className="text-6xl mb-4">
              {getResultIcon()}
            </div>
            <h3 className={`text-2xl font-bold mb-2 ${getResultColor()}`}>
              {getResultTitle()}
            </h3>
            <p className="text-gray-700 mb-4">
              {result.explanation}
            </p>
            
            {/* Confidence Bar */}
            <div className="max-w-md mx-auto">
              <div className="flex justify-between items-center mb-2">
                <span className="text-sm font-medium text-gray-600">Confidence</span>
                <span className="text-sm font-bold text-gray-800">{confidence}%</span>
              </div>
              {getConfidenceBar()}
            </div>
          </div>
        </div>
  
        {/* Additional Details */}
        {result.details && (
          <div className="bg-gray-50 rounded-lg p-4 mb-6">
            <h4 className="font-semibold text-gray-800 mb-2">Technical Details:</h4>
            <div className="space-y-2">
              {result.details.model_used && (
                <div className="flex justify-between">
                  <span className="text-gray-600">Model:</span>
                  <span className="font-medium">{result.details.model_used}</span>
                </div>
              )}
              {result.details.processing_time && (
                <div className="flex justify-between">
                  <span className="text-gray-600">Processing Time:</span>
                  <span className="font-medium">{result.details.processing_time}s</span>
                </div>
              )}
              {result.details.file_size && (
                <div className="flex justify-between">
                  <span className="text-gray-600">File Size:</span>
                  <span className="font-medium">{result.details.file_size}</span>
                </div>
              )}
            </div>
          </div>
        )}
  
        {/* What this means */}
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
          <h4 className="font-semibold text-blue-800 mb-2">💡 What this means:</h4>
          <p className="text-blue-700 text-sm">
            {isAiGenerated ? (
              confidence > 80 ? 
              "This content shows strong signs of being created by AI. It may have been generated by tools like Midjourney, DALL·E, or similar AI systems." :
              "This content has some characteristics of AI-generated media, but the result is not definitive. Consider the source and context."
            ) : (
              confidence > 80 ? 
              "This content appears to be authentic and likely created by traditional means (camera, real recording, etc.)." :
              "The analysis couldn't determine with high confidence whether this is real or AI-generated. This could be due to image quality, compression, or other factors."
            )}
          </p>
        </div>
  
        {/* Actions */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <button
            onClick={onReset}
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-3 px-8 rounded-lg transition-colors duration-200 shadow-lg hover:shadow-xl"
          >
            🔄 Analyze Another File
          </button>
          
          <button
            onClick={() => {
              const resultText = `AI Content Detector Results:
  File: ${fileName}
  Result: ${getResultTitle()}
  Confidence: ${confidence}%
  Explanation: ${result.explanation}
  
  Generated by AI Content Detector`;
              
              if (navigator.share) {
                navigator.share({
                  title: 'AI Content Detector Results',
                  text: resultText,
                });
              } else {
                navigator.clipboard.writeText(resultText);
                alert('Results copied to clipboard!');
              }
            }}
            className="bg-gray-600 hover:bg-gray-700 text-white font-medium py-3 px-8 rounded-lg transition-colors duration-200 shadow-lg hover:shadow-xl"
          >
            📋 Share Results
          </button>
        </div>
  
        {/* Disclaimer */}
        <div className="mt-6 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
          <p className="text-sm text-yellow-800 text-center">
            <strong>⚠️ Disclaimer:</strong> This tool provides estimates based on current AI detection methods. 
            Results should be considered alongside other factors and are not 100% definitive.
          </p>
        </div>
      </div>
    );
  };
  
  export default ResultDisplay;